### ISSUE TITLE
Bug: Sending a Factura

### ISSUE THREAD

**Issue by japstones** [rolandopalermo/veronica#14]
I sent a Factura to services but I getting a error.

![image](https://user-images.githubusercontent.com/3452663/50865805-3c94d900-1375-11e9-9d93-45efad0039fb.png)

**Comment by rolandopalermo** [comment]
Update the import statement for the NotEmpty annotation to
`import org.hibernate.validator.constraints.NotEmpty;`

**Comment by japstones** [comment]
Thanks!
