### ISSUE TITLE
Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection

### ISSUE THREAD

**Issue by darkane188** [rolandopalermo/veronica#18]
{
  "timestamp": 1548457345694,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.orm.jpa.JpaSystemException",
  "message": "Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection",
  "path": "/veronica/api/v1.0/facturas"
}
no se porque sucede eso tal vez es por alguna libreria que falta?

**Comment by XaviMontero** [comment]
Buenas noches amigo perdón por la demora , ¿si configuraste  veronica/veronica-web/src/main/resources/application.properties   con tus puertos , usuario y contraseña ?
