### ISSUE TITLE
Dependencia dto no encontrada

### ISSUE THREAD

**Issue by ericsilvapaucar** [rolandopalermo/veronica#2]
Cuando quiero compilar estoy teniendo este problema
![screen shot 2018-10-30 at 11 21 36 am](https://user-images.githubusercontent.com/15257762/47733379-0c72e080-dc36-11e8-9bd5-f42da28c2dd8.png)

**Comment by rolandopalermo** [comment]
Please, make a pull and try again

**Comment by ericsilvapaucar** [comment]
Persiste el problema
![screen shot 2018-10-30 at 11 34 53 am](https://user-images.githubusercontent.com/15257762/47734247-fe25c400-dc37-11e8-86cc-8de9e97da6f0.png)

**Comment by rolandopalermo** [comment]
It looks like an old piece of code was the problem. Please, make a pull.

**Comment by ericsilvapaucar** [comment]
Thanks you, that worked

**Comment by ericsilvapaucar** [comment]
![screen shot 2018-10-30 at 11 51 17 am](https://user-images.githubusercontent.com/15257762/47735246-2a424480-dc3a-11e8-97f5-51134a11c89d.png)

mvn spring-boot:run

**Comment by rolandopalermo** [comment]
https://github.com/rolandopalermo/veronica#deployment
