### ISSUE TITLE
como guardar una firma digital en la base de datos? 

### ISSUE THREAD

**Issue by darkane188** [rolandopalermo/veronica#23]
no tengo idea de como guardarla tal vez me podrían ayudar como seria el metodo de guardarla

**Comment by XaviMontero** [comment]
Muy buenas amigo, con respecto a tu pregunta. Tienes que generar en base 64  la firma digital  algo como esto. 
![image](https://user-images.githubusercontent.com/24358710/55293076-b0b0ad00-53b7-11e9-95f6-67fef0283053.png)
una ves generado la firma, la guardas con una consulta sql, con su respectiva clave de acceso

**Comment by darkane188** [comment]
gracias amigo si ayer mismo investigando hice justo lo mismo y ya solucione ese error gracias igualmente

**Comment by XaviMontero** [comment]
Un gusto.
