### ISSUE TITLE
Como se podria modificar una consulta sql ? de la api

### ISSUE THREAD

**Issue by darkane188** [rolandopalermo/veronica#25]
![image](https://user-images.githubusercontent.com/10376033/55513905-73088a00-562c-11e9-9c07-23760e459c2c.png)

**Comment by XaviMontero** [comment]
Buenas tardes amigo, las consultas son generadas en el paquete.
package com.rolandopalermo.facturacion.ec.persistence.repository .
Puedes entrar en la clase JpaRepository  para que te des una idea.

**Comment by darkane188** [comment]
![image](https://user-images.githubusercontent.com/10376033/55524990-d73f4400-5654-11e9-873b-d582f711f5b3.png)
que tal amigo te refieres a esta clase aun no entiendo muy bien donde se encuenttra el codigo para poder  modificar la consulta, lo que sucede es que quiero quitarle la parte donde encripta la contraseña de la firma digital que esta en la consulta q se muestra en la imagen , quiero establecerla directamente en el codigo y no extraerla del archivo de configuracion de postgres
