### ISSUE TITLE
Error en clave de acceso generada

### ISSUE THREAD

**Issue by vperilla** [rolandopalermo/veronica#27]
Teniendo el establecimiento 001 y punto de emisión 002:

Al formar la clave de acceso, una parte de la misma consiste en un número
serial formado por el establecimiento y punto de emisión:
lo correcto es 001-002
actualmente veronica genera 002-001

**Comment by vperilla** [comment]
#26 soluciona el error

**Comment by rolandopalermo** [comment]
Merge completo, muchas gracias por tu contribución al proyecto
