### ISSUE TITLE
Se puede hacer liquidaciones de compra?

### ISSUE THREAD

**Issue by rober7o** [rolandopalermo/veronica#30]
Hola tiene disponible las lisquidaciones de compra?

**Comment by israteneda** [comment]
Al parecer si según lo que se puede ver en el archivo de creación de base de datos de `veronica.sql`:
```
INSERT INTO PUBLIC.receipt_type (code, description) VALUES 
('01', 'FACTURA'),
('02', 'NOTA VENTA'),
('03', 'LIQ. DE COMPRA'),
('04', 'NOTA DE CRÉDITO'),
('05', 'NOTA DE DÉBITO'),
('06', 'GUÍA DE REMISIÓN'),
('07', 'COMPROBANTE DE RETENCIÓN'),
('11', 'TICKETS AEREOS'),
('12', 'DOCS INST. FINAN'),
('19', 'COMP PAGO CUOTAS'),
('20', 'DOCS SERV ADMIN'),
('41', 'COMP. REEMBOLSO');
```

**Comment by rolandopalermo** [comment]
Las dependencias para el soporte de liquidaciones ya se encuentran disponibles en:

- https://github.com/rolandopalermo/veronica-model
- https://github.com/rolandopalermo/veronica-jaxb
- https://github.com/rolandopalermo/veronica-dto

Estaría pendiente la integración en este proyecto.

**Comment by rolandopalermo** [comment]
También recuerda que tenemos la versión licenciada de Verónica la cual ya cuenta con liquidaciones de compra entre otras mejoras. Te adjunto el link de Swagger:
https://ec-sbox.rolandopalermo.com/facturacion/swagger-ui.html

**Comment by israteneda** [comment]
Sale un mensaje: "Tu conexión a este sitio no es segura". Supongo que es porque no está en https.
