### ISSUE TITLE
Error verificacion de archivo pkcs12

### ISSUE THREAD

**Issue by vperilla** [rolandopalermo/veronica#4]
En el controlador SRI, se realiza la verificacion de que exista el archivo pkcs12, pero estoy enviando
el path del archivo desde mi request.
https://github.com/rolandopalermo/veronica/blob/14dacd5a24de035d4ea3e0be5602e53ffb8c83c2/veronica-web/src/main/java/com/rolandopalermo/facturacion/ec/web/controller/SriController.java#L53

Considero que se debería hacer lo mismo que en el controlador de firma en el que se pregunta si 
la ruta del archivo es parte del request
https://github.com/rolandopalermo/veronica/blob/14dacd5a24de035d4ea3e0be5602e53ffb8c83c2/veronica-web/src/main/java/com/rolandopalermo/facturacion/ec/web/controller/FirmaController.java#L43

PD: me encuentro integrando veronica con Tryton -> [www.tryton.org](http://www.tryton.org)

**Comment by rolandopalermo** [comment]
Good feedback, please update your local repository with the last changes

**Comment by vperilla** [comment]
thanks!!!
