### ISSUE TITLE
Límite de caracteres en contraseña

### ISSUE THREAD

**Issue by luisadriantt** [rolandopalermo/veronica#41]
El servicio de crear certificado valida que la contraseña sea de un máximo de 15 caracteres, sin embargo, existen contraseñas para las firmas con más de 15 caracteres. Por favor, revisar

**Comment by vperilla** [comment]
Tengo entendido que el problema está en el jar veronica-dto-1.0.5.jar, adjunto dos imágenes que pueden clarificar el error, entiendo que la solución sería cambiar el valor de la variable max en CertifiacdoDigitalDTO.
![error2](https://user-images.githubusercontent.com/211490/102547259-f0855f80-4086-11eb-9edb-6f1a86855477.jpeg)
![error1](https://user-images.githubusercontent.com/211490/102546979-77860800-4086-11eb-9137-36fd15292264.jpeg)

**Comment by XaviMontero** [comment]
Crear un dto y apuntar al servicio  
![Captura de pantalla de 2020-12-17 19-06-22](https://user-images.githubusercontent.com/24358710/102558278-1ae11800-409b-11eb-8986-cb10c13f0dbc.png)

**Comment by luisadriantt** [comment]
> Crear un dto y apuntar al servicio
> ![Captura de pantalla de 2020-12-17 19-06-22](https://user-images.githubusercontent.com/24358710/102558278-1ae11800-409b-11eb-8986-cb10c13f0dbc.png)

Gracias Xavi! Cierro el issue
