### ISSUE TITLE
Envio de Factura - LocalHost

### ISSUE THREAD

**Issue by OscarHMG** [rolandopalermo/veronica#47]
![image](https://user-images.githubusercontent.com/6440245/130518385-7a2c1043-46d7-4b33-b49f-758bb41b6658.png)
 Estoy utilizando el archivo JSON de postman para probar los endpoints, con los DTO de ejemplo. Pude levantar el proyecto sin problemas, pero al momento de enviar una factura; tengo el error de la imagen.

Existe alguna configuracion inicial para poder hacer el envio?

Muchas Gracias!

**Comment by XaviMontero** [comment]
Hola que tal, sabes por lo que veo esta mal el password de la firma electrónica.

**Comment by OscarHMG** [comment]
Muchas gracias!
